import Input from './JrInput';
import Button from './JrButton';
import Checkbox from './JrCheckbox';
import Dialog from './JrDialog';
import Form from './JrForm';
import Message from './JrMessage';
import Confirm from './JrConfirm';
import Panel from './JrPanel';
import Tree from './JrTree';
import Editor from './JrEditor';
import Upload from './JrUpload';
import Grid from './JrGrid';
import QueryGridPage from './JrQueryGridPage';

export const JrInput = Input;
export const JrButton = Button;
export const JrCheckbox = Checkbox;
export const JrDialog = Dialog;
export const JrForm = Form;
export const JrMessage = Message;
export const JrConfirm = Confirm;
export const JrPanel = Panel;
export const JrTree = Tree;
export const JrEditor = Editor;
export const JrUpload = Upload;
export const JrGrid = Grid;
export const JrQueryGridPage = QueryGridPage;
