export const ALL_TODOS = "ALL_TODOS";
export const COMPLETED_TODOS = "COMPLETED_TODOS";
export const ACTIVE_TODOS = "ACTIVE_TODOS";

export const ADD_TODO = "ADD_TODO";
export const TOGGLE_COMPLETED_TODO = "TOGGLE_COMPLETED_TODO";
export const TOGGLE_ALL_TODO = "TOGGLE_ALL_TODO";
export const CLEAR_COMPLETED_TODO = "CLEAR_COMPLETED_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const CHANGENOWSHOWINGFILTER = "CHANGENOWSHOWINGFILTER";
